# Site settings
title: Rido in .Net
email: me@ridoin.net
description: "Rido Web Lab"
url: "http://g.ridoin.net"
twitter_username: ridomin
github_username:  ridomin
facebook_username:  ridomin

# Build settings
markdown: markdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
